import { Metadata } from "next";

export const metadata: Metadata = {
	title: {
		absolute: "",
		default: "Metadata title - default",
		template: "%s | Sanjeet",
	},
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<header style={{ padding: "20px", background: "gray" }}>Header</header>
				{children}
				<footer style={{ padding: "20px", background: "teal", marginTop: "2rem" }}>
					Footer
				</footer>
			</body>
		</html>
	);
}
